-- Tabla de configuración: matriz de transiciones válidas de ORDEN.ESTADO.
-- Es la autoridad final que consulta SP_ACTUALIZAR_ESTADO_ORDEN (V4); debe mantenerse
-- sincronizada con com.sysman.ordenes.dominio.modelo.EstadoOrden (ver docs/decisiones-tecnicas.md).
CREATE TABLE ORDEN_TRANSICION_VALIDA (
    ESTADO_ORIGEN  VARCHAR2(30) NOT NULL,
    ESTADO_DESTINO VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_TRANSICION_VALIDA PRIMARY KEY (ESTADO_ORIGEN, ESTADO_DESTINO)
);

INSERT INTO ORDEN_TRANSICION_VALIDA (ESTADO_ORIGEN, ESTADO_DESTINO) VALUES ('CREADA', 'ASIGNADA');
INSERT INTO ORDEN_TRANSICION_VALIDA (ESTADO_ORIGEN, ESTADO_DESTINO) VALUES ('CREADA', 'CANCELADA');
INSERT INTO ORDEN_TRANSICION_VALIDA (ESTADO_ORIGEN, ESTADO_DESTINO) VALUES ('ASIGNADA', 'EN_PROCESO');
INSERT INTO ORDEN_TRANSICION_VALIDA (ESTADO_ORIGEN, ESTADO_DESTINO) VALUES ('ASIGNADA', 'CANCELADA');
INSERT INTO ORDEN_TRANSICION_VALIDA (ESTADO_ORIGEN, ESTADO_DESTINO) VALUES ('EN_PROCESO', 'COMPLETADA');
INSERT INTO ORDEN_TRANSICION_VALIDA (ESTADO_ORIGEN, ESTADO_DESTINO) VALUES ('EN_PROCESO', 'CANCELADA');
